name: Docker Image CD

on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: write
      packages: write
      actions: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          CURRENT_VERSION=$(cat version.txt)
          BASE_VERSION=${CURRENT_VERSION%.*}
          MINOR_VERSION=${CURRENT_VERSION##*.}
          NEW_MINOR_VERSION=$((MINOR_VERSION + 1))
          NEW_VERSION="$BASE_VERSION.$NEW_MINOR_VERSION"
          echo $NEW_VERSION > version.txt
          docker build --target prod -t citywalkerdev/mongo:$NEW_VERSION \
            --build-arg MDB_USERNAME=${{ secrets.MDB_USERNAME }} \
            --build-arg MDB_PASSWORD=${{ secrets.MDB_PASSWORD }} .
          docker build --target test -t citywalkerdev/mongo-test:$NEW_VERSION .
          docker tag citywalkerdev/mongo:$NEW_VERSION citywalkerdev/mongo:latest
          docker tag citywalkerdev/mongo-test:$NEW_VERSION citywalkerdev/mongo-test:latest
          docker push citywalkerdev/mongo:$NEW_VERSION
          docker push citywalkerdev/mongo:latest
          docker push citywalkerdev/mongo-test:latest
          docker push citywalkerdev/mongo-test:$NEW_VERSION

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Bump version to $VERSION"
          add: "version.txt"

      # - name: Commit and push version update
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.TOKEN }}
      #   run: |
      #     git config --global user.email "actions@github.com"
      #     git config --global user.name "GitHub Actions"
      #     git add version.txt
      #     git commit -m "Bump version to $VERSION"
      #     git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
